export const en = {
  common: {
    continue: 'Continue',
    skip: 'Skip',
    next: 'Next',
    back: 'Back',
    done: 'Done',
    cancel: 'Cancel',
    save: 'Save',
    apply: 'Apply',
    search: 'Search',
    directions: 'Directions',
    call: 'Call',
    viewAll: 'View all',
    seeAll: 'See all',
    retry: 'Retry',
    loading: 'Loading…',
    open: 'Open',
    closed: 'Closed',
    km: 'km',
  },
  onboarding: {
    slide1Title: 'One app for everyday life',
    slide1Body: 'Health, areas, fuel, schemes, utilities and emergencies — all in one place.',
    slide2Title: 'Just ask — by text or voice',
    slide2Body: 'Your AI assistant understands your day and answers with real, local information.',
    slide3Title: 'Act in one tap',
    slide3Body: 'Get directions, apply, set reminders or call — instantly from any answer.',
    chooseLanguage: 'Choose your language',
    getStarted: 'Get started',
  },
  auth: {
    loginTitle: 'Enter your email',
    loginSubtitle: 'We will send you a 6-digit OTP to verify.',
    emailPlaceholder: 'Email address',
    sendOtp: 'Send OTP',
    otpTitle: 'Verify your email',
    otpSubtitle: 'Enter the 6-digit code sent to',
    resendIn: 'Resend code in',
    resend: 'Resend OTP',
    verify: 'Verify & continue',
    biometricTitle: 'Unlock instantly',
    biometricSubtitle: 'Use Face / fingerprint to re-enter the app privately.',
    useBiometric: 'Use biometric unlock',
    useOtpInstead: 'Use OTP instead',
    permTitle: 'Enable location',
    permSubtitle: 'Location powers all your "near me" answers — pharmacies, fuel, areas and help nearby.',
    allowLocation: 'Allow location',
    enterManually: 'Enter my area manually',
  },
  tabs: {
    home: 'Home',
    explore: 'Explore',
    travel: 'Travel',
    government: 'Government',
    profile: 'Profile',
  },
  home: {
    greeting: 'Namaste',
    searchPlaceholders: [
      'Find medicines near me…',
      'Check fuel prices nearby…',
      'Am I eligible for a scheme?',
      'Is Baner a good area?',
      'Any power cuts today?',
    ],
    quickActions: 'Quick actions',
    recentSearches: 'Recent searches',
    localAlerts: 'Local alerts',
    noRecents: 'Your recent searches will appear here.',
  },
  chat: {
    title: 'AI Assistant',
    emptyGreeting: 'How can I help you today?',
    emptySub: 'Ask me anything about your day — I understand your area, health, schemes and more.',
    inputPlaceholder: 'Ask anything…',
    thinking: 'Thinking…',
    suggestions: [
      'Find Dolo 650 near me',
      'Least crowded petrol pump',
      'Housing schemes I qualify for',
      'Is Baner a safe area?',
    ],
  },
  explore: {
    title: 'Area Intelligence',
    searchPlaceholder: 'Search an area, e.g. Baner, Pune',
    areaScore: 'Area Score',
    categories: 'Category breakdown',
    property: 'Property & cost',
    nearby: 'Nearby',
    avgRent: 'Avg rent',
    avgPrice: 'Avg price',
    priceGrowth: 'Price growth',
    builderRating: 'Builder rating',
    hospitals: 'Hospitals',
    schools: 'Schools',
    police: 'Police',
    atms: 'ATMs',
    compareCta: 'Ask AI to compare areas',
  },
  travel: {
    title: 'Travel & Fuel',
    stations: 'Stations near you',
    leastCrowded: 'Least crowded first',
    roadTrip: 'Road-trip planner',
    roadTripPlaceholder: 'e.g. Mumbai → Goa',
    plan: 'Plan trip',
    perLitre: '/L',
    crowdLow: 'Low',
    crowdMedium: 'Medium',
    crowdHigh: 'High',
  },
  government: {
    title: 'Government Schemes',
    prompt: 'What are you looking for?',
    categories: 'Browse by category',
    checkEligibility: 'Check my eligibility',
    eligibilityTitle: 'Eligibility checker',
    age: 'Age',
    occupation: 'Occupation',
    income: 'Annual income',
    state: 'State',
    gender: 'Gender',
    runCheck: 'Find schemes for me',
    results: 'Matching schemes',
    requiredDocs: 'Required documents',
    eligible: 'Eligible',
    maybe: 'May qualify',
    ineligible: 'Not eligible',
  },
  health: {
    title: 'Health & Medicines',
    searchPlaceholder: 'Search a medicine, e.g. Dolo 650',
    pharmaciesNearby: 'Pharmacies nearby',
    inStock: 'In stock',
    outOfStock: 'Out of stock',
    genericAlt: 'Generic alternative',
    dosage: 'Dosage guide',
    setReminder: 'Set reminder',
    scanPrescription: 'Scan prescription',
    disclaimer: 'Guidance only. Consult a doctor or pharmacist before taking any medicine.',
    saveMoney: 'Save {pct}%',
  },
  emergency: {
    title: 'Emergency',
    subtitle: 'Works without sign-in, even on low signal.',
    ambulance: 'Ambulance',
    police: 'Police',
    fire: 'Fire',
    women: 'Women Helpline',
    sos: 'SOS',
    sosHint: 'Hold to share live location with 112 & your contacts',
    sosCountdown: 'Sharing location in',
    sosActive: 'SOS active — location shared',
    cancel: 'Cancel',
    nearbyHelp: 'Nearby help',
    hospital: 'Hospital',
    bloodBank: 'Blood bank',
    policeStation: 'Police station',
  },
  utilities: {
    title: 'Utilities',
    power: 'Power cuts',
    water: 'Water supply',
    bookTanker: 'Book water tanker',
    scheduled: 'Scheduled',
    reported: 'Reported outage',
  },
  profile: {
    title: 'Profile',
    saved: 'Saved',
    medicines: 'Medicines',
    areas: 'Areas',
    routes: 'Routes',
    schemes: 'Schemes',
    settings: 'Settings',
    darkMode: 'Dark mode',
    language: 'Language',
    notifications: 'Notifications',
    privacy: 'Privacy',
    aiPersonality: 'AI personality',
    deleteData: 'Delete my data',
    editProfile: 'Edit profile',
    logout: 'Log out',
  },
  personalities: {
    friendly: 'Friendly',
    concise: 'Concise',
    formal: 'Formal',
    detailed: 'Detailed',
  },
};

export type Translation = typeof en;
