import {Translation} from './en';

/** Hindi strings. Launch languages per spec: English + Hindi. */
export const hi: Translation = {
  common: {
    continue: 'आगे बढ़ें',
    skip: 'छोड़ें',
    next: 'अगला',
    back: 'वापस',
    done: 'पूर्ण',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    apply: 'आवेदन करें',
    search: 'खोजें',
    directions: 'रास्ता',
    call: 'कॉल करें',
    viewAll: 'सभी देखें',
    seeAll: 'सभी देखें',
    retry: 'पुनः प्रयास',
    loading: 'लोड हो रहा है…',
    open: 'खुला',
    closed: 'बंद',
    km: 'कि.मी.',
  },
  onboarding: {
    slide1Title: 'रोज़मर्रा की ज़िंदगी के लिए एक ऐप',
    slide1Body: 'स्वास्थ्य, इलाके, ईंधन, योजनाएँ, सुविधाएँ और आपातकाल — सब एक जगह।',
    slide2Title: 'बस पूछें — टेक्स्ट या आवाज़ से',
    slide2Body: 'आपका AI सहायक आपके दिन को समझता है और सही, स्थानीय जानकारी देता है।',
    slide3Title: 'एक टैप में काम करें',
    slide3Body: 'किसी भी उत्तर से तुरंत रास्ता पाएं, आवेदन करें, रिमाइंडर लगाएं या कॉल करें।',
    chooseLanguage: 'अपनी भाषा चुनें',
    getStarted: 'शुरू करें',
  },
  auth: {
    loginTitle: 'अपना मोबाइल नंबर दर्ज करें',
    loginSubtitle: 'हम सत्यापन के लिए 6 अंकों का OTP भेजेंगे।',
    phonePlaceholder: 'मोबाइल नंबर',
    sendOtp: 'OTP भेजें',
    otpTitle: 'अपना नंबर सत्यापित करें',
    otpSubtitle: 'इस नंबर पर भेजा गया 6 अंकों का कोड दर्ज करें',
    resendIn: 'दोबारा भेजें',
    resend: 'OTP दोबारा भेजें',
    verify: 'सत्यापित करें और आगे बढ़ें',
    biometricTitle: 'तुरंत अनलॉक करें',
    biometricSubtitle: 'निजी तौर पर ऐप में दोबारा आने के लिए फेस / फिंगरप्रिंट का उपयोग करें।',
    useBiometric: 'बायोमेट्रिक अनलॉक',
    useOtpInstead: 'इसके बजाय OTP',
    permTitle: 'लोकेशन चालू करें',
    permSubtitle: 'लोकेशन आपके "मेरे पास" उत्तरों को सक्षम करती है — दवाइयाँ, ईंधन, इलाके और नज़दीकी मदद।',
    allowLocation: 'लोकेशन की अनुमति दें',
    enterManually: 'इलाका खुद दर्ज करें',
  },
  tabs: {
    home: 'होम',
    explore: 'एक्सप्लोर',
    travel: 'यात्रा',
    government: 'सरकारी',
    profile: 'प्रोफ़ाइल',
  },
  home: {
    greeting: 'नमस्ते',
    searchPlaceholders: [
      'मेरे पास दवाइयाँ खोजें…',
      'नज़दीकी ईंधन की कीमत देखें…',
      'क्या मैं किसी योजना के योग्य हूँ?',
      'क्या बानेर अच्छा इलाका है?',
      'आज कोई बिजली कटौती है?',
    ],
    quickActions: 'त्वरित क्रियाएँ',
    recentSearches: 'हाल की खोजें',
    localAlerts: 'स्थानीय अलर्ट',
    noRecents: 'आपकी हाल की खोजें यहाँ दिखेंगी।',
  },
  chat: {
    title: 'AI सहायक',
    emptyGreeting: 'आज मैं आपकी कैसे मदद करूँ?',
    emptySub: 'अपने दिन के बारे में कुछ भी पूछें — मैं आपका इलाका, स्वास्थ्य, योजनाएँ और बहुत कुछ समझता हूँ।',
    inputPlaceholder: 'कुछ भी पूछें…',
    thinking: 'सोच रहा हूँ…',
    suggestions: [
      'मेरे पास Dolo 650 खोजें',
      'सबसे कम भीड़ वाला पेट्रोल पंप',
      'मेरे लिए आवास योजनाएँ',
      'क्या बानेर सुरक्षित इलाका है?',
    ],
  },
  explore: {
    title: 'इलाका जानकारी',
    searchPlaceholder: 'इलाका खोजें, जैसे बानेर, पुणे',
    areaScore: 'इलाका स्कोर',
    categories: 'श्रेणी विवरण',
    property: 'संपत्ति और लागत',
    nearby: 'नज़दीकी',
    avgRent: 'औसत किराया',
    avgPrice: 'औसत कीमत',
    priceGrowth: 'कीमत वृद्धि',
    builderRating: 'बिल्डर रेटिंग',
    hospitals: 'अस्पताल',
    schools: 'स्कूल',
    police: 'पुलिस',
    atms: 'एटीएम',
    compareCta: 'AI से इलाकों की तुलना कराएँ',
  },
  travel: {
    title: 'यात्रा और ईंधन',
    stations: 'आपके पास स्टेशन',
    leastCrowded: 'सबसे कम भीड़ पहले',
    roadTrip: 'रोड-ट्रिप प्लानर',
    roadTripPlaceholder: 'जैसे मुंबई → गोवा',
    plan: 'यात्रा प्लान करें',
    perLitre: '/ली',
    crowdLow: 'कम',
    crowdMedium: 'मध्यम',
    crowdHigh: 'ज़्यादा',
  },
  government: {
    title: 'सरकारी योजनाएँ',
    prompt: 'आप क्या खोज रहे हैं?',
    categories: 'श्रेणी से देखें',
    checkEligibility: 'मेरी पात्रता जाँचें',
    eligibilityTitle: 'पात्रता जाँचकर्ता',
    age: 'आयु',
    occupation: 'व्यवसाय',
    income: 'वार्षिक आय',
    state: 'राज्य',
    gender: 'लिंग',
    runCheck: 'मेरे लिए योजनाएँ खोजें',
    results: 'मिलती-जुलती योजनाएँ',
    requiredDocs: 'आवश्यक दस्तावेज़',
    eligible: 'योग्य',
    maybe: 'योग्य हो सकते हैं',
    ineligible: 'योग्य नहीं',
  },
  health: {
    title: 'स्वास्थ्य और दवाइयाँ',
    searchPlaceholder: 'दवा खोजें, जैसे Dolo 650',
    pharmaciesNearby: 'नज़दीकी फार्मेसी',
    inStock: 'स्टॉक में',
    outOfStock: 'स्टॉक ख़त्म',
    genericAlt: 'जेनेरिक विकल्प',
    dosage: 'खुराक मार्गदर्शन',
    setReminder: 'रिमाइंडर लगाएं',
    scanPrescription: 'पर्चा स्कैन करें',
    disclaimer: 'केवल मार्गदर्शन। कोई भी दवा लेने से पहले डॉक्टर या फार्मासिस्ट से सलाह लें।',
    saveMoney: '{pct}% बचाएं',
  },
  emergency: {
    title: 'आपातकाल',
    subtitle: 'बिना साइन-इन के, कम सिग्नल पर भी काम करता है।',
    ambulance: 'एम्बुलेंस',
    police: 'पुलिस',
    fire: 'फायर',
    women: 'महिला हेल्पलाइन',
    sos: 'SOS',
    sosHint: '112 और अपने संपर्कों के साथ लाइव लोकेशन साझा करने के लिए दबाए रखें',
    sosCountdown: 'लोकेशन साझा होने में',
    sosActive: 'SOS सक्रिय — लोकेशन साझा की गई',
    cancel: 'रद्द करें',
    nearbyHelp: 'नज़दीकी मदद',
    hospital: 'अस्पताल',
    bloodBank: 'ब्लड बैंक',
    policeStation: 'पुलिस स्टेशन',
  },
  utilities: {
    title: 'सुविधाएँ',
    power: 'बिजली कटौती',
    water: 'पानी आपूर्ति',
    bookTanker: 'पानी टैंकर बुक करें',
    scheduled: 'निर्धारित',
    reported: 'सूचित कटौती',
  },
  profile: {
    title: 'प्रोफ़ाइल',
    saved: 'सहेजे गए',
    medicines: 'दवाइयाँ',
    areas: 'इलाके',
    routes: 'रास्ते',
    schemes: 'योजनाएँ',
    settings: 'सेटिंग्स',
    darkMode: 'डार्क मोड',
    language: 'भाषा',
    notifications: 'सूचनाएँ',
    privacy: 'गोपनीयता',
    aiPersonality: 'AI व्यक्तित्व',
    deleteData: 'मेरा डेटा हटाएं',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    logout: 'लॉग आउट',
  },
  personalities: {
    friendly: 'मित्रवत',
    concise: 'संक्षिप्त',
    formal: 'औपचारिक',
    detailed: 'विस्तृत',
  },
};
